package com.example.logo2palette

import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Path
import android.graphics.RectF
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import androidx.core.content.FileProvider
import com.example.logo2palette.model.ColorPalette
import com.example.logo2palette.utils.ColorUtils
import java.io.File
import java.io.FileOutputStream

object PdfReportGenerator {

    fun createReport(
        context: Context,
        logo: Bitmap,
        palette: ColorPalette,
        paletteNumber: Int
    ): File {

        val document = PdfDocument()

        // =========================================================
        // PAGE 1: Brand Identity & Swatches
        // =========================================================
        val pageInfo1 = PdfDocument.PageInfo.Builder(595, 842, 1).create()
        val page1 = document.startPage(pageInfo1)
        val canvas1 = page1.canvas
        val paint = Paint(Paint.ANTI_ALIAS_FLAG)

        drawPageHeader(canvas1, paint, "Brand Color System", paletteNumber)
        drawLogoSection(canvas1, paint, logo)
        drawSwatchesSection(canvas1, paint, palette)
        drawCodeTokensSummary(canvas1, paint, palette)
        drawFooter(canvas1, paint, 1, 2)
        document.finishPage(page1)

        // =========================================================
        // PAGE 2: Website UI & Mobile App UI Mockup Previews
        // =========================================================
        val pageInfo2 = PdfDocument.PageInfo.Builder(595, 842, 2).create()
        val page2 = document.startPage(pageInfo2)
        val canvas2 = page2.canvas

        drawPageHeader(canvas2, paint, "UI Previews & Mockups", paletteNumber)
        drawWebsitePreviewSection(canvas2, paint, palette, 40f, 90f)
        drawMobilePreviewSection(canvas2, paint, palette, 40f, 420f)
        drawFooter(canvas2, paint, 2, 2)
        document.finishPage(page2)

        // Save PDF to cache directory
        val directory = File(context.cacheDir, "reports")
        if (!directory.exists()) directory.mkdirs()

        val file = File(directory, "Logo2Palette_Brand_Report.pdf")
        FileOutputStream(file).use { output ->
            document.writeTo(output)
        }
        document.close()

        return file
    }

    // =========================================================
    // PAGE HEADER & FOOTER
    // =========================================================

    private fun drawPageHeader(canvas: Canvas, paint: Paint, subtitle: String, paletteNumber: Int) {
        canvas.drawColor(Color.WHITE)

        // Top Accent Bar
        paint.color = Color.rgb(103, 80, 164)
        canvas.drawRect(0f, 0f, 595f, 8f, paint)

        // Title
        paint.color = Color.rgb(28, 27, 31)
        paint.textSize = 24f
        paint.typeface = Typeface.DEFAULT_BOLD
        canvas.drawText("Logo2Palette", 40f, 45f, paint)

        // Subtitle
        paint.color = Color.rgb(111, 107, 118)
        paint.textSize = 12f
        paint.typeface = Typeface.DEFAULT
        canvas.drawText(subtitle, 40f, 64f, paint)

        // Palette Number Pill
        paint.color = Color.rgb(238, 235, 244)
        canvas.drawRoundRect(450f, 30f, 555f, 60f, 15f, 15f, paint)

        paint.color = Color.rgb(103, 80, 164)
        paint.textSize = 11f
        paint.typeface = Typeface.DEFAULT_BOLD
        canvas.drawText("Palette #$paletteNumber", 465f, 49f, paint)

        // Divider Line
        paint.color = Color.rgb(230, 230, 235)
        canvas.drawLine(40f, 75f, 555f, 75f, paint)
    }

    private fun drawFooter(canvas: Canvas, paint: Paint, pageNum: Int, totalPages: Int) {
        paint.color = Color.rgb(230, 230, 235)
        canvas.drawLine(40f, 805f, 555f, 805f, paint)

        paint.color = Color.rgb(140, 140, 145)
        paint.textSize = 10f
        paint.typeface = Typeface.DEFAULT
        canvas.drawText("Generated by Logo2Palette • Smart Web & Mobile Color System", 40f, 822f, paint)
        canvas.drawText("Page $pageNum of $totalPages", 500f, 822f, paint)
    }

    // =========================================================
    // LOGO & SWATCHES (PAGE 1)
    // =========================================================

    private fun drawLogoSection(canvas: Canvas, paint: Paint, logo: Bitmap) {
        paint.color = Color.rgb(28, 27, 31)
        paint.textSize = 14f
        paint.typeface = Typeface.DEFAULT_BOLD
        canvas.drawText("BRAND LOGO SOURCE", 40f, 100f, paint)

        // Card frame around logo
        paint.color = Color.rgb(248, 247, 252)
        canvas.drawRoundRect(40f, 110f, 555f, 220f, 16f, 16f, paint)

        val softwareLogo = if (logo.config == Bitmap.Config.HARDWARE) {
            logo.copy(Bitmap.Config.ARGB_8888, false)
        } else logo

        val maxDimension = 90f
        val ratio = minOf(maxDimension / softwareLogo.width, maxDimension / softwareLogo.height)
        val logoWidth = softwareLogo.width * ratio
        val logoHeight = softwareLogo.height * ratio
        val logoLeft = (595f - logoWidth) / 2f
        val logoTop = 110f + (110f - logoHeight) / 2f

        canvas.drawBitmap(
            softwareLogo,
            null,
            RectF(logoLeft, logoTop, logoLeft + logoWidth, logoTop + logoHeight),
            paint
        )
    }

    private fun drawSwatchesSection(canvas: Canvas, paint: Paint, palette: ColorPalette) {
        paint.color = Color.rgb(28, 27, 31)
        paint.textSize = 14f
        paint.typeface = Typeface.DEFAULT_BOLD
        canvas.drawText("EXTRACTED DESIGN TOKENS & WCAG RATIOS", 40f, 245f, paint)

        val swatches = listOf(
            Triple("PRIMARY", palette.primary, palette.onPrimary),
            Triple("SECONDARY", palette.secondary, palette.onSecondary),
            Triple("ACCENT", palette.accent, palette.onAccent),
            Triple("BACKGROUND", palette.background, palette.onBackground),
            Triple("SURFACE", palette.surface, palette.onSurface),
            Triple("TEXT PRIMARY", palette.textPrimary, palette.background)
        )

        var xPos = 40f
        var yPos = 260f

        swatches.forEachIndexed { index, (role, hex, contrastTarget) ->
            if (index > 0 && index % 2 == 0) {
                xPos = 40f
                yPos += 75f
            } else if (index % 2 == 1) {
                xPos = 300f
            }

            drawPdfSwatchCard(canvas, paint, role, hex, xPos, yPos)
        }
    }

    private fun drawPdfSwatchCard(
        canvas: Canvas,
        paint: Paint,
        role: String,
        hex: String,
        x: Float,
        y: Float
    ) {
        val color = try { Color.parseColor(hex) } catch (e: Exception) { Color.GRAY }
        val textColorInt = ColorUtils.getContrastTextColor(color)
        val ratio = ColorUtils.calculateContrastRatio(textColorInt, color)
        val badge = ColorUtils.getWcagBadge(ratio)

        // Card Container Background
        paint.color = Color.rgb(250, 250, 252)
        canvas.drawRoundRect(x, y, x + 250f, y + 65f, 12f, 12f, paint)

        // Color Swatch Circle
        paint.color = color
        canvas.drawRoundRect(x + 10f, y + 10f, x + 55f, y + 55f, 12f, 12f, paint)

        // Role Label
        paint.color = Color.rgb(28, 27, 31)
        paint.textSize = 12f
        paint.typeface = Typeface.DEFAULT_BOLD
        canvas.drawText(role, x + 65f, y + 26f, paint)

        // HEX & WCAG Rating
        paint.color = Color.rgb(110, 110, 120)
        paint.textSize = 10f
        paint.typeface = Typeface.DEFAULT
        canvas.drawText("$hex  •  $badge", x + 65f, y + 46f, paint)
    }

    private fun drawCodeTokensSummary(canvas: Canvas, paint: Paint, palette: ColorPalette) {
        val startY = 500f
        paint.color = Color.rgb(28, 27, 31)
        paint.textSize = 14f
        paint.typeface = Typeface.DEFAULT_BOLD
        canvas.drawText("DEVELOPER CODE EXPORT SNIPPET", 40f, startY, paint)

        // Dark Code Container
        paint.color = Color.rgb(30, 30, 36)
        canvas.drawRoundRect(40f, startY + 15f, 555f, startY + 280f, 16f, 16f, paint)

        paint.color = Color.rgb(160, 230, 160)
        paint.textSize = 11f
        paint.typeface = Typeface.MONOSPACE

        val cssLines = ColorUtils.toCssVariables(palette).split("\n")
        var lineY = startY + 40f
        cssLines.forEach { line ->
            if (lineY < startY + 270f) {
                canvas.drawText(line, 55f, lineY, paint)
                lineY += 16f
            }
        }
    }

    // =========================================================
    // WEBSITE PREVIEW (PAGE 2 - TOP SECTION)
    // =========================================================

    private fun drawWebsitePreviewSection(
        canvas: Canvas,
        paint: Paint,
        palette: ColorPalette,
        x: Float,
        y: Float
    ) {
        val bgInt = try { Color.parseColor(palette.background) } catch (e: Exception) { Color.WHITE }
        val primaryInt = try { Color.parseColor(palette.primary) } catch (e: Exception) { Color.BLUE }
        val secondaryInt = try { Color.parseColor(palette.secondary) } catch (e: Exception) { Color.MAGENTA }
        val accentInt = try { Color.parseColor(palette.accent) } catch (e: Exception) { Color.YELLOW }
        val surfaceInt = try { Color.parseColor(palette.surface) } catch (e: Exception) { Color.WHITE }
        val textPrimaryInt = try { Color.parseColor(palette.textPrimary) } catch (e: Exception) { Color.BLACK }

        val onPrimary = ColorUtils.getContrastTextColor(primaryInt)
        val onAccent = ColorUtils.getContrastTextColor(accentInt)

        paint.color = Color.rgb(28, 27, 31)
        paint.textSize = 14f
        paint.typeface = Typeface.DEFAULT_BOLD
        canvas.drawText("🌐 WEBSITE UI PREVIEW (DESKTOP MOCKUP)", x, y, paint)

        val frameTop = y + 15f
        val frameWidth = 515f
        val frameHeight = 280f

        // Outer Frame Border
        paint.color = Color.rgb(220, 220, 230)
        canvas.drawRoundRect(x, frameTop, x + frameWidth, frameTop + frameHeight, 16f, 16f, paint)

        // Web Canvas Fill
        paint.color = bgInt
        canvas.drawRoundRect(x + 2f, frameTop + 2f, x + frameWidth - 2f, frameTop + frameHeight - 2f, 14f, 14f, paint)

        // 1. Navigation Bar
        paint.color = primaryInt
        canvas.drawRoundRect(x + 2f, frameTop + 2f, x + frameWidth - 2f, frameTop + 45f, 14f, 14f, paint)

        paint.color = onPrimary
        paint.textSize = 14f
        paint.typeface = Typeface.DEFAULT_BOLD
        canvas.drawText("Logo2Palette Website", x + 20f, frameTop + 28f, paint)

        paint.textSize = 10f
        paint.typeface = Typeface.DEFAULT
        canvas.drawText("Home    Products    About    Contact", x + 340f, frameTop + 28f, paint)

        // 2. Hero Section
        // Accent Pill
        paint.color = accentInt
        canvas.drawRoundRect(x + 20f, frameTop + 62f, x + 150f, frameTop + 82f, 10f, 10f, paint)

        paint.color = onAccent
        paint.textSize = 9f
        paint.typeface = Typeface.DEFAULT_BOLD
        canvas.drawText("BRAND COLOR SYSTEM", x + 30f, frameTop + 75f, paint)

        // Hero Title
        val guaranteedTitle = ColorUtils.ensureContrast(textPrimaryInt, bgInt, 7.0)
        paint.color = guaranteedTitle
        paint.textSize = 20f
        paint.typeface = Typeface.DEFAULT_BOLD
        canvas.drawText("Build something beautiful.", x + 20f, frameTop + 115f, paint)

        // Subtitle
        paint.color = ColorUtils.ensureContrast(Color.rgb(100, 100, 110), bgInt, 4.5)
        paint.textSize = 10f
        paint.typeface = Typeface.DEFAULT
        canvas.drawText("Responsive web application interface styled with logo design tokens.", x + 20f, frameTop + 135f, paint)

        // Primary Button
        paint.color = primaryInt
        canvas.drawRoundRect(x + 20f, frameTop + 150f, x + 130f, frameTop + 180f, 10f, 10f, paint)

        paint.color = onPrimary
        paint.textSize = 10f
        paint.typeface = Typeface.DEFAULT_BOLD
        canvas.drawText("Get Started →", x + 35f, frameTop + 168f, paint)

        // 3. Feature Cards (Right Side)
        val cardX = x + 310f
        paint.color = surfaceInt
        canvas.drawRoundRect(cardX, frameTop + 62f, x + 495f, frameTop + 175f, 12f, 12f, paint)

        val cardTextTitle = ColorUtils.ensureContrast(textPrimaryInt, surfaceInt, 7.0)
        paint.color = cardTextTitle
        paint.textSize = 12f
        paint.typeface = Typeface.DEFAULT_BOLD
        canvas.drawText("Feature Cards", cardX + 16f, frameTop + 85f, paint)

        paint.color = ColorUtils.ensureContrast(Color.rgb(120, 120, 130), surfaceInt, 4.5)
        paint.textSize = 9f
        paint.typeface = Typeface.DEFAULT
        canvas.drawText("100% WCAG contrast compliant.", cardX + 16f, frameTop + 105f, paint)

        paint.color = secondaryInt
        canvas.drawRect(cardX + 16f, frameTop + 120f, cardX + 160f, frameTop + 124f, paint)

        // 4. Bottom CTA Banner inside web frame
        paint.color = primaryInt
        canvas.drawRoundRect(x + 20f, frameTop + 200f, x + 495f, frameTop + 265f, 12f, 12f, paint)

        paint.color = onPrimary
        paint.textSize = 13f
        paint.typeface = Typeface.DEFAULT_BOLD
        canvas.drawText("Ready to export production code?", x + 35f, frameTop + 230f, paint)

        paint.color = onPrimary
        paint.textSize = 9f
        paint.typeface = Typeface.DEFAULT
        canvas.drawText("Copy CSS, Tailwind, Android XML, Compose, Flutter, or JSON.", x + 35f, frameTop + 248f, paint)
    }

    // =========================================================
    // MOBILE PREVIEW (PAGE 2 - BOTTOM SECTION)
    // =========================================================

    private fun drawMobilePreviewSection(
        canvas: Canvas,
        paint: Paint,
        palette: ColorPalette,
        x: Float,
        y: Float
    ) {
        val bgInt = try { Color.parseColor(palette.background) } catch (e: Exception) { Color.WHITE }
        val primaryInt = try { Color.parseColor(palette.primary) } catch (e: Exception) { Color.BLUE }
        val secondaryInt = try { Color.parseColor(palette.secondary) } catch (e: Exception) { Color.MAGENTA }
        val accentInt = try { Color.parseColor(palette.accent) } catch (e: Exception) { Color.YELLOW }
        val surfaceInt = try { Color.parseColor(palette.surface) } catch (e: Exception) { Color.WHITE }
        val textPrimaryInt = try { Color.parseColor(palette.textPrimary) } catch (e: Exception) { Color.BLACK }

        val onPrimary = ColorUtils.getContrastTextColor(primaryInt)
        val onAccent = ColorUtils.getContrastTextColor(accentInt)

        paint.color = Color.rgb(28, 27, 31)
        paint.textSize = 14f
        paint.typeface = Typeface.DEFAULT_BOLD
        canvas.drawText("📱 MOBILE APP UI PREVIEW (SMARTPHONE MOCKUP)", x, y, paint)

        val frameTop = y + 15f
        val frameWidth = 515f
        val frameHeight = 340f

        // Outer Mobile Frame Shell
        paint.color = Color.rgb(220, 220, 230)
        canvas.drawRoundRect(x, frameTop, x + frameWidth, frameTop + frameHeight, 16f, 16f, paint)

        // Mobile Screen Container
        paint.color = bgInt
        canvas.drawRoundRect(x + 2f, frameTop + 2f, x + frameWidth - 2f, frameTop + frameHeight - 2f, 14f, 14f, paint)

        // Phone Shell Mockup Container (Centered Smartphone Display)
        val phoneWidth = 230f
        val phoneLeft = x + (frameWidth - phoneWidth) / 2f
        val phoneTop = frameTop + 10f

        paint.color = Color.rgb(40, 40, 45)
        canvas.drawRoundRect(phoneLeft - 6f, phoneTop - 6f, phoneLeft + phoneWidth + 6f, phoneTop + 310f, 20f, 20f, paint)

        // Phone Screen Background
        paint.color = bgInt
        canvas.drawRoundRect(phoneLeft, phoneTop, phoneLeft + phoneWidth, phoneTop + 300f, 16f, 16f, paint)

        // 1. Mobile App Top Header
        paint.color = primaryInt
        canvas.drawRoundRect(phoneLeft, phoneTop, phoneLeft + phoneWidth, phoneTop + 50f, 16f, 16f, paint)

        paint.color = onPrimary
        paint.textSize = 8f
        paint.typeface = Typeface.DEFAULT
        canvas.drawText("9:41 AM  •  5G ⚡", phoneLeft + 12f, phoneTop + 16f, paint)

        paint.textSize = 12f
        paint.typeface = Typeface.DEFAULT_BOLD
        canvas.drawText("Mobile Dashboard", phoneLeft + 12f, phoneTop + 38f, paint)

        // 2. Category Filter Pills
        paint.color = accentInt
        canvas.drawRoundRect(phoneLeft + 12f, phoneTop + 62f, phoneLeft + 75f, phoneTop + 80f, 10f, 10f, paint)

        paint.color = onAccent
        paint.textSize = 8f
        paint.typeface = Typeface.DEFAULT_BOLD
        canvas.drawText("Overview", phoneLeft + 22f, phoneTop + 74f, paint)

        paint.color = surfaceInt
        canvas.drawRoundRect(phoneLeft + 82f, phoneTop + 62f, phoneLeft + 140f, phoneTop + 80f, 10f, 10f, paint)

        paint.color = ColorUtils.ensureContrast(textPrimaryInt, surfaceInt, 4.5)
        paint.textSize = 8f
        canvas.drawText("Analytics", phoneLeft + 92f, phoneTop + 74f, paint)

        // 3. Analytics Card Widget
        paint.color = surfaceInt
        canvas.drawRoundRect(phoneLeft + 12f, phoneTop + 92f, phoneLeft + phoneWidth - 12f, phoneTop + 175f, 12f, 12f, paint)

        val cardTitle = ColorUtils.ensureContrast(Color.rgb(100, 100, 110), surfaceInt, 4.5)
        paint.color = cardTitle
        paint.textSize = 9f
        paint.typeface = Typeface.DEFAULT
        canvas.drawText("Weekly Impressions", phoneLeft + 22f, phoneTop + 112f, paint)

        val statText = ColorUtils.ensureContrast(primaryInt, surfaceInt, 4.5)
        paint.color = statText
        paint.textSize = 20f
        paint.typeface = Typeface.DEFAULT_BOLD
        canvas.drawText("128,450", phoneLeft + 22f, phoneTop + 138f, paint)

        val subStatText = ColorUtils.ensureContrast(secondaryInt, surfaceInt, 4.5)
        paint.color = subStatText
        paint.textSize = 8f
        paint.typeface = Typeface.DEFAULT_BOLD
        canvas.drawText("↑ +14.2% from last week", phoneLeft + 22f, phoneTop + 158f, paint)

        // 4. Action Item List Card
        paint.color = surfaceInt
        canvas.drawRoundRect(phoneLeft + 12f, phoneTop + 185f, phoneLeft + phoneWidth - 12f, phoneTop + 245f, 12f, 12f, paint)

        paint.color = primaryInt
        canvas.drawCircle(phoneLeft + 28f, phoneTop + 215f, 8f, paint)

        paint.color = ColorUtils.ensureContrast(textPrimaryInt, surfaceInt, 7.0)
        paint.textSize = 10f
        paint.typeface = Typeface.DEFAULT_BOLD
        canvas.drawText("Color System Validated", phoneLeft + 44f, phoneTop + 210f, paint)

        paint.color = ColorUtils.ensureContrast(Color.rgb(120, 120, 130), surfaceInt, 4.5)
        paint.textSize = 8f
        paint.typeface = Typeface.DEFAULT
        canvas.drawText("Passed WCAG AA compliance", phoneLeft + 44f, phoneTop + 226f, paint)

        // 5. Bottom Navigation Bar Simulation
        paint.color = surfaceInt
        canvas.drawRoundRect(phoneLeft, phoneTop + 265f, phoneLeft + phoneWidth, phoneTop + 300f, 14f, 14f, paint)

        paint.color = ColorUtils.ensureContrast(primaryInt, surfaceInt, 4.5)
        paint.textSize = 9f
        paint.typeface = Typeface.DEFAULT_BOLD
        canvas.drawText("🏠 Home    📊 Stats    💬 Chat    👤 User", phoneLeft + 20f, phoneTop + 286f, paint)
    }

    fun sharePdf(context: Context, file: File) {
        val uri = FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "application/pdf"
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(intent, "Share Logo2Palette PDF Report"))
    }
}